version: '3.7'
services:
 postgresql:
   image: postgres:14.5-alpine
   restart: always
   container_name: backstage-development
   environment:
     - POSTGRES_DB=${POSTGRES_DB}
     - POSTGRES_HOST=${POSTGRES_HOST}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
   ports:
     - 5432:5432
   volumes:
     - pgdata:/data/postgres
volumes:
 pgdata:
   driver: local