# Grupo lab2dev com guest como membro e external como pai
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: lab2dev
  description: The lab2dev group
spec:
  type: team
  profile:
    displayName: Lab2Dev
    email: lab2dev@example.com
    picture: https://example.com/groups/lab2dev.jpeg
  # Defina que este grupo é filho do grupo external
  parent: external
  children: []
  members: [guest, alexandrejuniorc]
