---
# Usuário guest associado ao grupo developers
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
  annotations:
    backstage.io/email: guest@example.com
spec:
  memberOf: [developers]
---
# Usuário alexandrejuniorc associado ao grupo lab2dev
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: alexandrejuniorc
  annotations:
    backstage.io/email: alejunior.dev@gmail.com
spec:
  memberOf: [lab2dev]
